# Generated by Django 4.2.6 on 2023-10-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_questions', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('answer', models.TextField(blank=True)),
                ('time_create', models.DateTimeField()),
            ],
        ),
    ]
