# Generated by Django 4.2.6 on 2023-10-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='time_create',
            field=models.DateTimeField(blank=True),
        ),
    ]
